name: deploy to ghcr.io
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
          push: true
          cache-from: type=registry,ref=${{ github.repository_owner }}/build-node:${{ env.NODE_VERSION }}
          cache-to: type=inline
          tags: |
            ghcr.io/${{ github.repository_owner }}/build-node:latest
            ghcr.io/${{ github.repository_owner }}/build-node:${{ env.NODE_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
